package com.example.dishdash.model.response;

public class Converter {

    public static FoodPlan convertToPlanClass(Food food, String date) {
        return new FoodPlan(food.getMealId(),
                        food.getMealName(),
                food.getDrinkAlternate(),
                food.getCategory(),
                food.getArea(),
                food.getInstructions(),
                food.getMealThumbnail(),
                food.getTags(),
                food.getYoutubeUrl(),
                food.getIngredient1(),
                food.getIngredient2(),
                food.getIngredient3(),
                food.getIngredient4(),
                food.getIngredient5(),
                food.getIngredient6(),
                food.getIngredient7(),
                food.getIngredient8(),
                food.getIngredient9(),
                food.getIngredient10(),
                food.getIngredient11(),
                food.getIngredient12(),
                food.getIngredient13(),
                food.getIngredient14(),
                food.getIngredient15(),
                food.getIngredient16(),
                food.getIngredient17(),
                food.getIngredient18(),
                food.getIngredient19(),
                food.getIngredient20(),
                food.getMeasure1(),
                food.getMeasure2(),
                food.getMeasure3(),
                food.getMeasure4(),
                food.getMeasure5(),
                food.getMeasure6(),
                food.getMeasure7(),
                food.getMeasure8(),
                food.getMeasure9(),
                food.getMeasure10(),
                food.getMeasure11(),
                food.getMeasure12(),
                food.getMeasure13(),
                food.getMeasure14(),
                food.getMeasure15(),
                food.getMeasure16(),
                food.getMeasure17(),
                food.getMeasure18(),
                food.getMeasure19(),
                food.getMeasure20(),
                food.getSource(),
                food.getImageSource(),
                food.getCreativeCommonsConfirmed(),
                food.getDateModified(),
                food.isFav(),
                date);
    }
}